# Generated by Django 5.0 on 2023-12-15 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adress_store",
                to="booking.store",
            ),
        ),
        migrations.AddField(
            model_name="adress",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adress_user",
                to="booking.user",
            ),
        ),
    ]
