# Generated by Django 5.0 on 2023-12-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_store_adress_alter_store_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="adress",
        ),
        migrations.RemoveField(
            model_name="store",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="user",
            name="adress",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact",
        ),
        migrations.AddField(
            model_name="contact",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.store",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.user",
            ),
        ),
    ]
