# Generated by Django 5.0 on 2024-01-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_rename_adress_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="bike_user",
                serialize=False,
                to="booking.user",
            ),
        ),
    ]
