# Generated by Django 5.0 on 2023-12-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_remove_store_adress_remove_store_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                ("brand", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=30)),
                ("year", models.CharField(max_length=4)),
                ("sn", models.CharField(max_length=30)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="booking.user",
                    ),
                ),
            ],
        ),
    ]
